on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container
      - uses: aws-actions/setup-sam@v1
        with:
          version: 1.23.0

# Run Unit tests- Specify unit tests here 
    - run: sam build --use-container
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset


# sam deploy
      # - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name github-actions-with-aws-sam --s3-bucket cicd-pipelines --capabilities CAPABILITY_IAM --region us-east-1
